# Version of docker-compose
version: "3.8"

# Containers we are going to run
services:
  # Our Golang container
  api:
    image: deeplobe-api
    # The build parameters for this container.
    # Here we define that it should build from the current directory
    build:
      context: ./
    ports:
      - "80:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/deeplobe_api/data
      - ./deeplobe_ai:/app/deeplobe_ai
    depends_on:
      - redis
    command: bash deploy.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    command: >
      --requirepass deeplobe
      --timeout 0
      --protected-mode yes
    volumes:
      - ./data:/app/deeplobe_api/data
      - ./deeplobe_ai:/app/deeplobe_ai

  rq-worker:
    image: deeplobe-api
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/deeplobe_api/data
    command: bash rqworker.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute
