# Generated by Django 3.2 on 2021-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210526_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('OCR', 'ocr'), ('IMAGE_CLASSIFICATION', 'image_classification'), ('OBJECT_DETECTION', 'object_detection'), ('IMAGE_SEGMENTATION', 'image_segmentation'), ('OTHERS', 'others')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
    ]
