# Generated by Django 3.2 on 2021-09-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20210913_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='type',
        ),
    ]
