# Generated by Django 3.2 on 2021-09-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_remove_register_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='type',
            field=models.JSONField(blank=True, choices=[('OCR', 'ocr'), ('IMAGE_CLASSIFICATION', 'image_classification'), ('OBJECT_DETECTION', 'object_detection'), ('IMAGE_SEGMENTATION', 'image_segmentation'), ('OTHERS', 'others')], default=list, null=True),
        ),
    ]
