# Generated by Django 3.2 on 2021-09-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_register_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='type',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
