# Generated by Django 3.2 on 2021-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
