# Generated by Django 3.2 on 2021-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_apikey_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='secret',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
