# Generated by Django 3.2 on 2021-10-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_apikey_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='application_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
