# Generated by Django 3.2 on 2021-10-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_apikey_application_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
