# Generated by Django 3.2 on 2021-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
