# Generated by Django 3.2 on 2021-11-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20211110_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='other_information',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
