# Generated by Django 3.2 on 2021-11-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_auto_20211112_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ckpt_file_path',
            field=models.FileField(blank=True, null=True, upload_to='model_memory'),
        ),
    ]
