# Generated by Django 3.2 on 2021-11-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_task_ckpt_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
