# Generated by Django 3.2 on 2021-11-30 12:43

import deeplobe_api.db.models.aimodel
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_auto_20211130_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('CLASSIFICATION', 'classification'), ('SEGMENTATION', 'segmentation'), ('IMAGE_SIMILARITY', 'image_similarity'), ('TAGGING', 'tagging'), ('OCR', 'ocr'), ('INSTANCE', 'instance')], max_length=255)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('weight_file', models.FileField(blank=True, null=True, upload_to=deeplobe_api.db.models.aimodel.get_upload_path)),
                ('annotation_file', models.FileField(blank=True, null=True, upload_to=deeplobe_api.db.models.aimodel.get_upload_path)),
                ('data', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_trained', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AIModel',
                'verbose_name_plural': 'AIModels',
                'db_table': 'aimodels',
                'ordering': ['-created'],
            },
        ),
    ]
