# Generated by Django 3.2 on 2021-12-01 05:15

import deeplobe_api.db.models.aimodel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='key_file',
            field=models.FileField(blank=True, null=True, upload_to=deeplobe_api.db.models.aimodel.get_upload_path),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('classification', 'CLASSIFICATION'), ('segmentation', 'SEGMENTATION'), ('image_similarity', 'IMAGE_SIMILARITY'), ('tagging', 'TAGGING'), ('ocr', 'OCR'), ('instance', 'INSTANCE')], max_length=255),
        ),
    ]
