# Generated by Django 3.2 on 2021-12-01 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_auto_20211201_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_images', models.JSONField()),
                ('result', models.JSONField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_predicted', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('aimodel', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='db.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AIModelPrediction',
                'verbose_name_plural': 'AIModelPredictions',
                'db_table': 'aimodelpredictions',
                'ordering': ['-created'],
            },
        ),
    ]
