# Generated by Django 3.2 on 2021-12-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_aimodelprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelprediction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aimodelprediction',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
