# Generated by Django 3.2 on 2021-12-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_alter_aimodel_weight_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='class_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
