# Generated by Django 3.2 on 2021-12-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_mediaasset_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_file'),
        ),
    ]
