# Generated by Django 3.2 on 2022-01-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_alter_support_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='media_file'),
        ),
    ]
