# Generated by Django 3.2 on 2022-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_contactus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
