# Generated by Django 3.2 on 2022-02-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_user_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
