# Generated by Django 3.2 on 2022-02-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_alter_user_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interestedIn',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
