# Generated by Django 3.2 on 2022-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0036_user_interestedin"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="job",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
