# Generated by Django 3.2 on 2022-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
    ]
