# Generated by Django 3.2 on 2022-03-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_aimodel_aws_weight_file'),
        ('db', '0039_auto_20220228_1446'),
    ]

    operations = [
    ]
