# Generated by Django 3.2 on 2022-03-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_merge_20220301_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
