# Generated by Django 3.2 on 2022-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_auto_20220302_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='failed_reason',
            field=models.JSONField(default=dict),
        ),
    ]
