# Generated by Django 3.2 on 2022-03-21 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_user_extended_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('model_type', models.CharField(choices=[('custom_classification', 'CUSTOM_CLASSIFICATION'), ('custom_segmentation', 'CUSTOM_SEGMENTATION'), ('custom_image_similarity', 'CUSTOM_IMAGE_SIMILARITY'), ('custom_tagging', 'CUSTOM_TAGGING'), ('custom_ocr', 'CUSTOM_OCR'), ('custom_instance', 'CUSTOM_INSTANCE'), ('pre_sentimental_analysis', 'PRE_SENTIMENTAL_ANALYSIS'), ('pre_image_similarity ', 'PRE_IMAGE_SIMILARITY'), ('pre_facial_detection', 'PRE_FACIAL_DETECTION'), ('pre_demographic_recognition', 'PRE_DEMOGRAPHIC_RECOGNITION'), ('pre_facial_expression', 'PRE_FACIAL_EXPRESSION'), ('pre_pose_detection', 'PRE_POSE_DETECTION'), ('pre_text_moderation', 'PRE_TEXT_MODERATION'), ('pre_people_vehicle_detection', 'PRE_PEOPLE_VEHICLE_DETECTION'), ('pre_wound_detection', 'PRE_WOUND_DETECTION')], max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_loggers', to='db.apikey')),
            ],
            options={
                'verbose_name': 'APILogger',
                'verbose_name_plural': 'APILoggers',
                'db_table': 'apiloggers',
            },
        ),
    ]
