# Generated by Django 3.2 on 2022-03-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0044_apilogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogger',
            name='is_custom_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apilogger',
            name='model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aimodel_id', to='db.aimodel'),
        ),
        migrations.AlterField(
            model_name='apilogger',
            name='model_type',
            field=models.CharField(choices=[('custom_classification', 'CUSTOM_CLASSIFICATION'), ('custom_segmentation', 'CUSTOM_SEGMENTATION'), ('custom_image_similarity', 'CUSTOM_IMAGE_SIMILARITY'), ('custom_tagging', 'CUSTOM_TAGGING'), ('custom_ocr', 'CUSTOM_OCR'), ('custom_instance', 'CUSTOM_INSTANCE'), ('pre_sentimental_analysis', 'PRE_SENTIMENTAL_ANALYSIS'), ('pre_image_similarity', 'PRE_IMAGE_SIMILARITY'), ('pre_facial_detection', 'PRE_FACIAL_DETECTION'), ('pre_demographic_recognition', 'PRE_DEMOGRAPHIC_RECOGNITION'), ('pre_facial_expression', 'PRE_FACIAL_EXPRESSION'), ('pre_pose_detection', 'PRE_POSE_DETECTION'), ('pre_text_moderation', 'PRE_TEXT_MODERATION'), ('pre_people_vehicle_detection', 'PRE_PEOPLE_VEHICLE_DETECTION'), ('pre_wound_detection', 'PRE_WOUND_DETECTION')], max_length=255),
        ),
    ]
