# Generated by Django 3.2 on 2022-09-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_autoannotatepredictionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_permissions',
            field=models.JSONField(default=list),
        ),
    ]
