# Generated by Django 3.2 on 2022-11-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apikey',
            table='api_keys',
        ),
    ]
