# Generated by Django 3.2 on 2022-12-20 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0050_alter_mediaasset_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeBeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('email', models.JSONField(default=list)),
                ('customer_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ChargeBee',
                'verbose_name_plural': ' ChargeBees',
                'db_table': 'chargebee',
            },
        ),
        migrations.CreateModel(
            name='APICount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_model_api_count', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APICount',
                'verbose_name_plural': 'APICounts',
                'db_table': 'apicounts',
            },
        ),
    ]
