# Generated by Django 3.2 on 2022-12-29 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_auto_20221223_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('is_collaborator', models.BooleanField(default=False)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_collaborator', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invitee', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Collaborator',
                'verbose_name_plural': 'Subscription Collaborators',
                'db_table': 'subscription_collaborators',
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionCollobarator',
        ),
    ]
