# Generated by Django 3.2 on 2022-12-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0057_auto_20221229_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
