# Generated by Django 3.2 on 2022-12-29 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0060_subscriptioncollaborator_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioncollaborator',
            name='workspace',
        ),
        migrations.CreateModel(
            name='WorkspaceCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('Workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Collaborator',
                'verbose_name_plural': 'Workspaces Collaborators',
                'db_table': 'workspace_collaborators',
            },
        ),
    ]
