# Generated by Django 3.2 on 2022-12-29 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0061_auto_20221229_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioncollaborator',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.workspace'),
        ),
    ]
