# Generated by Django 3.2 on 2022-12-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0062_subscriptioncollaborator_workspace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkspaceCollaborator',
        ),
    ]
