# Generated by Django 3.2 on 2022-12-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0063_delete_workspacecollaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogger',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.workspace'),
        ),
    ]
