# Generated by Django 3.2 on 2023-01-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0064_apilogger_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_workspace',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
