# Generated by Django 3.2 on 2023-01-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0065_user_current_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.workspace'),
        ),
    ]
