# Generated by Django 3.2 on 2023-01-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0068_auto_20230118_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargeBeeModel',
        ),
        migrations.DeleteModel(
            name='UserInvitation',
        ),
    ]
