# Generated by Django 3.2 on 2023-01-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0069_auto_20230118_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portal_code',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='GSTIN',
            field=models.TextField(blank=True, null=True),
        ),
    ]
