# Generated by Django 3.2 on 2023-01-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0070_auto_20230119_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_country', models.BooleanField(default=False)),
                ('parent_location', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(max_length=255, unique=True)),
                ('currency_symbol', models.CharField(max_length=255, unique=True)),
                ('iso', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_country', models.BooleanField(default=False)),
                ('parent_name', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'states',
            },
        ),
    ]
