# Generated by Django 3.2 on 2023-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0072_auto_20230119_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
