# Generated by Django 3.2 on 2023-01-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0073_alter_user_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bussiness_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
