# Generated by Django 3.2 on 2023-01-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0074_user_bussiness_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='help',
            field=models.BooleanField(default=True),
        ),
    ]
