# Generated by Django 3.2 on 2023-01-30 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0075_user_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('resolved', 'RESOLVED')], default='pending', max_length=255)),
                ('ticket_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.support')),
            ],
            options={
                'verbose_name': 'SupportTicket',
                'verbose_name_plural': 'SupportTickets',
                'db_table': 'support_tickets',
            },
        ),
    ]
