# Generated by Django 3.2 on 2023-02-07 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0076_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('collaborator_email', models.CharField(blank=True, max_length=256, null=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_new_invitee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NewUserInvitation',
                'verbose_name_plural': 'NewUserInvitations',
                'db_table': 'new_user_invitations',
            },
        ),
    ]
