# Generated by Django 3.2 on 2023-02-08 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0077_newuserinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationHireExpertRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('withdrawn', 'WITHDRAWN'), ('assigned', 'ASSIGNED'), ('pending', 'PENDING'), ('resolved', 'RESOLVED'), ('open', 'OPEN'), ('closed', 'CLOSED'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('contacted', 'CONTACTED'), ('uncontacted', 'UNCONTACTED')], default='new', max_length=255)),
            ],
            options={
                'verbose_name': 'Annotation Hire Expert Request',
                'verbose_name_plural': 'Annotation Hire Expert Requests',
                'db_table': 'annotation_hire_expert_requests',
            },
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ('created',), 'verbose_name': 'Support', 'verbose_name_plural': 'Supports'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='requested_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('withdrawn', 'WITHDRAWN'), ('assigned', 'ASSIGNED'), ('pending', 'PENDING'), ('resolved', 'RESOLVED'), ('open', 'OPEN'), ('closed', 'CLOSED'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('contacted', 'CONTACTED'), ('uncontacted', 'UNCONTACTED')], default='new', max_length=255),
        ),
        migrations.AddField(
            model_name='support',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('withdrawn', 'WITHDRAWN'), ('assigned', 'ASSIGNED'), ('pending', 'PENDING'), ('resolved', 'RESOLVED'), ('open', 'OPEN'), ('closed', 'CLOSED'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('contacted', 'CONTACTED'), ('uncontacted', 'UNCONTACTED')], default='new', max_length=255),
        ),
    ]
