# Generated by Django 3.2.17 on 2023-02-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0080_auto_20230208_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationhireexpertrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotationhireexpertrequest',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
