# Generated by Django 3.2 on 2023-02-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0083_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='status',
            field=models.CharField(default='Draft', max_length=256),
        ),
    ]
