# Generated by Django 3.2.17 on 2023-03-15 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0084_aimodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('collaborator_email', models.CharField(blank=True, max_length=256, null=True)),
                ('is_collaborator', models.BooleanField(default=False)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitee', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.subscription')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'verbose_name': 'UserInvitation',
                'verbose_name_plural': 'User Invitations',
                'db_table': 'user_invitations',
            },
        ),
        migrations.RemoveField(
            model_name='subscriptioncollaborator',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='subscriptioncollaborator',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='subscriptioncollaborator',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptioncollaborator',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='NewUserInvitation',
        ),
        migrations.DeleteModel(
            name='SubscriptionCollaborator',
        ),
    ]
