# Generated by Django 3.2 on 2023-03-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0085_auto_20230315_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('classification', 'CLASSIFICATION'), ('segmentation', 'SEGMENTATION'), ('image_similarity', 'IMAGE_SIMILARITY'), ('object_detection', 'OBJECT_DETECTION'), ('ocr', 'OCR'), ('instance', 'INSTANCE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='apilogger',
            name='model_type',
            field=models.CharField(choices=[('custom_classification', 'CUSTOM_CLASSIFICATION'), ('custom_segmentation', 'CUSTOM_SEGMENTATION'), ('custom_image_similarity', 'CUSTOM_IMAGE_SIMILARITY'), ('custom_object_detection', 'CUSTOM_OBJECT_DETECTION'), ('custom_ocr', 'CUSTOM_OCR'), ('custom_instance', 'CUSTOM_INSTANCE'), ('pre_sentimental_analysis', 'PRE_SENTIMENTAL_ANALYSIS'), ('pre_image_similarity', 'PRE_IMAGE_SIMILARITY'), ('pre_facial_detection', 'PRE_FACIAL_DETECTION'), ('pre_demographic_recognition', 'PRE_DEMOGRAPHIC_RECOGNITION'), ('pre_facial_expression', 'PRE_FACIAL_EXPRESSION'), ('pre_pose_detection', 'PRE_POSE_DETECTION'), ('pre_text_moderation', 'PRE_TEXT_MODERATION'), ('pre_people_vehicle_detection', 'PRE_PEOPLE_VEHICLE_DETECTION'), ('pre_wound_detection', 'PRE_WOUND_DETECTION')], max_length=255),
        ),
    ]
