# Generated by Django 3.2 on 2023-03-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0086_auto_20230320_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='api_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
