# Generated by Django 3.2 on 2023-03-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0087_aimodel_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilogger',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apilogger',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
