# Generated by Django 3.2 on 2023-03-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0088_auto_20230327_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogger',
            name='response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
