# Generated by Django 3.2 on 2023-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0090_auto_20230410_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='models',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
