# Generated by Django 3.2 on 2023-04-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0091_userinvitation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='model',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('user', 'model')},
        ),
    ]
