# Generated by Django 3.2 on 2023-04-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0092_auto_20230424_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='augmentation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='preproceesing',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
