# Generated by Django 3.2.14 on 2023-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_rename_preproceesing_aimodel_preprocessing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='model',
            new_name='aimodel',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='augmentation',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='preprocessing',
        ),
        migrations.AddField(
            model_name='apikey',
            name='pretrained_model',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('user', 'aimodel'), ('user', 'pretrained_model')},
        ),
    ]
