# Generated by Django 3.2.14 on 2023-05-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0095_auto_20230510_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription', models.JSONField(blank=True, default=dict, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.JSONField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('canceled_at', models.CharField(blank=True, max_length=255, null=True)),
                ('current_period_start', models.CharField(blank=True, max_length=255, null=True)),
                ('current_period_end', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.CharField(blank=True, max_length=255, null=True)),
                ('ended_at', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'StripeSubcription',
                'verbose_name_plural': ' StripeSubcriptions',
                'db_table': 'stripesubcription',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='subscription',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subcription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.stripesubcription'),
        ),
    ]
