# Generated by Django 3.2.14 on 2023-05-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0096_auto_20230512_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='key_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
