# Generated by Django 3.2.14 on 2023-05-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0097_alter_aimodel_key_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubcription',
            name='customer_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubcription',
            name='invoice_details',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apilogger',
            name='model_type',
            field=models.CharField(choices=[('classification', 'Custom Classification'), ('segmentation', 'Custom Segmentation'), ('image_similarity', 'Custom Image Similarity'), ('object_detection', 'Custom Object detection'), ('ocr', 'Custom OCR'), ('instance', 'Custom Instance'), ('pre_sentimental_analysis', 'PRE_SENTIMENTAL_ANALYSIS'), ('pre_image_similarity', 'PRE_IMAGE_SIMILARITY'), ('pre_facial_detection', 'PRE_FACIAL_DETECTION'), ('pre_demographic_recognition', 'PRE_DEMOGRAPHIC_RECOGNITION'), ('pre_facial_expression', 'PRE_FACIAL_EXPRESSION'), ('pre_pose_detection', 'PRE_POSE_DETECTION'), ('pre_text_moderation', 'PRE_TEXT_MODERATION'), ('pre_people_vehicle_detection', 'PRE_PEOPLE_VEHICLE_DETECTION'), ('pre_wound_detection', 'PRE_WOUND_DETECTION')], max_length=255),
        ),
    ]
