# Generated by Django 3.2.14 on 2023-05-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0098_auto_20230518_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesubcription',
            name='invoice_details',
        ),
        migrations.RemoveField(
            model_name='stripesubcription',
            name='price_id',
        ),
        migrations.AlterField(
            model_name='stripesubcription',
            name='stripe_customer_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripesubcription',
            name='stripe_subscription_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubcriptionInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('invoice_details', models.JSONField(blank=True, max_length=255, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.stripesubcription')),
            ],
            options={
                'verbose_name': 'SubscriptionInvoices',
                'verbose_name_plural': ' SubscriptionInvoices',
                'db_table': 'subscriptionsinvoice',
            },
        ),
    ]
