# Generated by Django 3.2.14 on 2023-05-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0099_auto_20230523_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='augmentation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='preprocessing',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
