# Generated by Django 3.2.14 on 2023-05-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0100_auto_20230524_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
